services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/dev/Dockerfile
      args:
        - BUF_VERSION
        - CONTAINER_UID
        - CONTAINER_USER
        - GINKGO_VERSION
        - GO_VERSION
        - GOPLS_VERSION
        - HCP_VERSION
        - KIND_VERSION
        - NODE_VERSION
        - OPENSHIFT_VERSION
        - RUST_VERSION
        - WORKSPACE_DIR_NAME
        - YQ_VERSION
    image: dev-env:latest
    container_name: dev
    command: tail -f /dev/null
    environment:
      - USER=${CONTAINER_USER}
      - DEV_ENV_DIR
      - KEEPASS_DB_PATH
    volumes:
      - ${HOST_GENERAL_DIR}/.bash_history:/home/${CONTAINER_USER}/.bash_history
      - ${HOST_GENERAL_DIR}/.claude:/home/${CONTAINER_USER}/.claude
      - ${HOST_BINARIES_DIR}:/home/${CONTAINER_USER}/Binaries
      - ${HOST_REPOS_DIR}:/${REPOS_DIR_NAME}
      - ${HOST_WORKSPACE_DIR}:/${WORKSPACE_DIR_NAME}
    pids_limit: 8192
    networks:
      - dev-net

networks:
  dev-net:
