services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/dev/Dockerfile
      args:
        - ATUIN_VERSION
        - BUF_VERSION
        - CONTAINER_UID
        - CONTAINER_USER
        - GINKGO_VERSION
        - GO_VERSION
        - GOPLS_VERSION
        - GRPCURL_VERSION
        - HCP_VERSION
        - JQ_VERSION
        - KIND_VERSION
        - KUSTOMIZE_VERSION
        - NODE_VERSION
        - OPENSHIFT_VERSION
        - PODMAN_VERSION
        - RUST_VERSION
        - WORKSPACE_DIR_NAME
        - YQ_VERSION
        - ZELLIJ_VERSION
    image: dev-env:latest
    container_name: dev
    userns_mode: "keep-id"
    command: tail -f /dev/null
    environment:
      - USER=${CONTAINER_USER}
      - DEV_ENV_DIR
      - KEEPASS_DB_PATH
      - CONTAINER_HOST=unix:///var/run/podman/podman.sock
    volumes:
      - ${HOST_DEV_CLAUDE_DIR}:/home/${CONTAINER_USER}/.claude
      - ${HOST_DEV_CURSOR_DIR}:/home/${CONTAINER_USER}/.cursor
      - ${HOST_DEV_CODEX_DIR}:/home/${CONTAINER_USER}/.codex
      - ${HOST_DEV_ATUIN_CONFIG_DIR}:/home/${CONTAINER_USER}/.config/atuin
      - ${HOST_DEV_ATUIN_DATA_DIR}:/home/${CONTAINER_USER}/.local/share/atuin
      - ${HOST_DEV_ZELLIJ_CONFIG_DIR}:/home/${CONTAINER_USER}/.config/zellij
      - ${HOST_DEV_ZELLIJ_CACHE_DIR}:/home/${CONTAINER_USER}/.cache/zellij
      - ${HOST_BINARIES_DIR}:/home/${CONTAINER_USER}/Binaries
      - ${HOST_REPOS_DIR}:/${REPOS_DIR_NAME}
      - ${HOST_WORKSPACE_DIR}:/${WORKSPACE_DIR_NAME}
      - ${HOST_PODMAN_SOCK}:/var/run/podman/podman.sock
    networks:
      - dev-net
    cap_add:
      - NET_RAW
    security_opt:
      - label=disable

networks:
  dev-net:
